#!/bin/bash
#
# Postgres Initialization
#

BASEDIR=`dirname $0`
PWD=`pwd`

cd $BASEDIR

if [ -z "$DB" ]; then
  DB="eaglelogger"
fi

if [ "$force" == "true" ]; then
  psql -U postgres --quiet -c "DROP DATABASE $DB"
  psql -U postgres --quiet -c "DROP USER $DB"
fi

psql -U postgres --quiet -c "CREATE DATABASE $DB"
psql -U postgres --quiet -c "CREATE USER $DB WITH PASSWORD '$DB'"
psql -U postgres --quiet -d $DB -c "CREATE EXTENSION pg_trgm"

DB=$DB zipcodes/zipcodes
DB=$DB schema/schema

if [ "$fccdata" == "true" ]; then
  DB=$DB forcefcc=$forcefcc fccdata/fccdata
fi

if [ "$devdata" == "true" ]; then
  DB=$DB devdata/devdata
fi

cd $PWD
