DROP TABLE IF EXISTS fcc_l_amat_en;
CREATE TABLE fcc_l_amat_en (
  id serial NOT NULL,
  created timestamp DEFAULT current_timestamp NOT NULL,
  record_type char(2),
  usid numeric(9),
  uls char(14),
  ebf varchar(30),
  callsign char(10),
  type char(2),
  licensee_id char(9),
  name varchar(200),
  first_name varchar(20),
  middle_initial char(1),
  last_name varchar(20),
  suffix char(3),
  phone char(10),
  fax char(10),
  email varchar(50),
  address varchar(60),
  city varchar(20),
  state char(2),
  zip_code char(9),
  po_box varchar(20),
  attention_line varchar(35),
  sgin char(3),
  frn char(10),
  applicant_type char(1),
  applicant_type_other char(40),
  status_code char(1),
  status_date date,
  PRIMARY KEY (id),
  UNIQUE (usid)
);

DROP TABLE IF EXISTS fcc_l_amat_hd;
CREATE TABLE fcc_l_amat_hd (
  id serial NOT NULL,
  created timestamp DEFAULT current_timestamp NOT NULL,
  record_type char(2),
  usid numeric(9),
  uls char(14),
  ebf varchar(30),
  callsign char(10),
  status char(1),
  radio_service_code char(2),
  grant_date date,
  expired_date date,
  cancellation_date date,
  eligibility_rule_num char(10),
  reserved char(1),
  alien char(1),
  alien_government char(1),
  alien_corporation char(1),
  alien_officer char(1),
  alien_control char(1),
  revoked char(1),
  convicted char(1),
  adjudged char(1),
  reserved2 char(1),
  common_carrier char(1),
  non_common_carrier char(1),
  private_comm char(1),
  fixed char(1),
  mobile char(1),
  radiolocation char(1),
  satellite char(1),
  developmental_or_sta_or_demonstration char(1),
  interconnected_service char(1),
  certifier_first_name varchar(20),
  certifier_mi char(1),
  certifier_last_name varchar(20),
  certifier_suffix char(3),
  certifier_title char(40),
  female char(1),
  black_or_african_american char(1),
  native_american char(1),
  hawaiian char(1),
  asian char(1),
  white char(1),
  hispanic char(1),
  effective_date date,
  last_action_date date,
  auction_id int,
  broadcast_services_regulatory_status char(1),
  band_manager_regulatory_status char(1),
  broadcast_services_type_of_radio_service char(1),
  alien_ruling char(1),
  licensee_name_change char(1),
  PRIMARY KEY(id),
  UNIQUE (usid)
);

DROP MATERIALIZED VIEW IF EXISTS fcc_l_amat;
CREATE MATERIALIZED VIEW fcc_l_amat AS (
  SELECT
    fcc_l_amat_en.usid,
    fcc_l_amat_en.uls,
    fcc_l_amat_en.ebf,
    fcc_l_amat_en.callsign,
    fcc_l_amat_en.type,
    fcc_l_amat_en.licensee_id,
    fcc_l_amat_en.name,
    fcc_l_amat_en.first_name,
    fcc_l_amat_en.middle_initial,
    fcc_l_amat_en.last_name,
    fcc_l_amat_en.suffix,
    fcc_l_amat_en.phone,
    fcc_l_amat_en.fax,
    fcc_l_amat_en.email,
    fcc_l_amat_en.address,
    fcc_l_amat_en.city,
    fcc_l_amat_en.state,
    fcc_l_amat_en.zip_code,
    fcc_l_amat_en.po_box,
    fcc_l_amat_en.attention_line,
    fcc_l_amat_en.sgin,
    fcc_l_amat_en.frn,
    fcc_l_amat_en.applicant_type,
    fcc_l_amat_en.applicant_type_other,
    fcc_l_amat_en.status_code,
    fcc_l_amat_en.status_date,
    fcc_l_amat_hd.status,
    fcc_l_amat_hd.radio_service_code,
    fcc_l_amat_hd.grant_date,
    fcc_l_amat_hd.expired_date,
    fcc_l_amat_hd.cancellation_date,
    fcc_l_amat_hd.eligibility_rule_num,
    fcc_l_amat_hd.reserved,
    fcc_l_amat_hd.alien,
    fcc_l_amat_hd.alien_government,
    fcc_l_amat_hd.alien_corporation,
    fcc_l_amat_hd.alien_officer,
    fcc_l_amat_hd.alien_control,
    fcc_l_amat_hd.revoked,
    fcc_l_amat_hd.convicted,
    fcc_l_amat_hd.adjudged,
    fcc_l_amat_hd.reserved2,
    fcc_l_amat_hd.common_carrier,
    fcc_l_amat_hd.non_common_carrier,
    fcc_l_amat_hd.private_comm,
    fcc_l_amat_hd.fixed,
    fcc_l_amat_hd.mobile,
    fcc_l_amat_hd.radiolocation,
    fcc_l_amat_hd.satellite,
    fcc_l_amat_hd.developmental_or_sta_or_demonstration,
    fcc_l_amat_hd.interconnected_service,
    fcc_l_amat_hd.certifier_first_name,
    fcc_l_amat_hd.certifier_mi,
    fcc_l_amat_hd.certifier_last_name,
    fcc_l_amat_hd.certifier_suffix,
    fcc_l_amat_hd.certifier_title,
    fcc_l_amat_hd.female,
    fcc_l_amat_hd.black_or_african_american,
    fcc_l_amat_hd.native_american,
    fcc_l_amat_hd.hawaiian,
    fcc_l_amat_hd.asian,
    fcc_l_amat_hd.white,
    fcc_l_amat_hd.hispanic,
    fcc_l_amat_hd.effective_date,
    fcc_l_amat_hd.last_action_date,
    fcc_l_amat_hd.auction_id,
    fcc_l_amat_hd.broadcast_services_regulatory_status,
    fcc_l_amat_hd.band_manager_regulatory_status,
    fcc_l_amat_hd.broadcast_services_type_of_radio_service,
    fcc_l_amat_hd.alien_ruling,
    fcc_l_amat_hd.licensee_name_change
  FROM fcc_l_amat_en
  LEFT JOIN fcc_l_amat_hd ON fcc_l_amat_hd.usid = fcc_l_amat_en.usid
);
