DROP TABLE IF EXISTS fcc_l_amat_en;
CREATE TABLE fcc_l_amat_en (
  id serial NOT NULL,
  created timestamp DEFAULT current_timestamp NOT NULL,
  record_type char(2),
  usid numeric(9),
  uls char(14),
  ebf varchar(30),
  callsign char(10),
  type char(2),
  licensee_id char(9),
  name varchar(200),
  first_name varchar(20),
  middle_initial char(1),
  last_name varchar(20),
  suffix char(3),
  phone char(10),
  fax char(10),
  email varchar(50),
  address varchar(60),
  city varchar(20),
  state char(2),
  zip_code char(9),
  po_box varchar(20),
  attention_line varchar(35),
  sgin char(3),
  frn bigint,
  applicant_type char(1),
  applicant_type_other char(40),
  status_code char(1),
  status_date date,
  PRIMARY KEY (id),
  UNIQUE (usid)
);

DROP TABLE IF EXISTS fcc_l_amat_hd;
CREATE TABLE fcc_l_amat_hd (
  id serial NOT NULL,
  created timestamp DEFAULT current_timestamp NOT NULL,
  record_type char(2),
  usid numeric(9),
  uls char(14),
  ebf varchar(30),
  callsign char(10),
  status char(1),
  radio_service_code char(2),
  grant_date date,
  expired_date date,
  cancellation_date date,
  eligibility_rule_num char(10),
  reserved char(1),
  alien char(1),
  alien_government char(1),
  alien_corporation char(1),
  alien_officer char(1),
  alien_control char(1),
  revoked char(1),
  convicted char(1),
  adjudged char(1),
  reserved2 char(1),
  common_carrier char(1),
  non_common_carrier char(1),
  private_comm char(1),
  fixed char(1),
  mobile char(1),
  radiolocation char(1),
  satellite char(1),
  developmental_or_sta_or_demonstration char(1),
  interconnected_service char(1),
  certifier_first_name varchar(20),
  certifier_mi char(1),
  certifier_last_name varchar(20),
  certifier_suffix char(3),
  certifier_title char(40),
  female char(1),
  black_or_african_american char(1),
  native_american char(1),
  hawaiian char(1),
  asian char(1),
  white char(1),
  hispanic char(1),
  effective_date date,
  last_action_date date,
  auction_id int,
  broadcast_services_regulatory_status char(1),
  band_manager_regulatory_status char(1),
  broadcast_services_type_of_radio_service char(1),
  alien_ruling char(1),
  licensee_name_change char(1),
  PRIMARY KEY(id),
  UNIQUE (usid)
);
