#!/bin/bash
#
# FCC Database Retriever
# Import Steps:
#   1. create database & user
#   2. download database files
#   3. extract files
#   4. remove non-ascii characters
#   5. run import queries for each file
#   6. refresh joined view
#
# FCC database schema: http://wireless.fcc.gov/uls/documentation/pa_ddef50.pdf

BASEDIR=`dirname $0`
cd $BASEDIR

# create temp directory
if [ ! -d "tmp" ]; then
  mkdir tmp
fi

# download data
DAY=`date --date="yesterday" +%a | tr '[:upper:]' '[:lower:]'`
l_amat_url="http://wireless.fcc.gov/uls/data/daily/l_am_$DAY.zip"
wget -O tmp/l_amat.zip $l_amat_url

# unzip
unzip -d tmp -o tmp/l_amat.zip

#clean
sed -i 's/\\|/|/' tmp/EN.dat
perl -pi -e 's/[^[:ascii:]]//g' tmp/EN.dat
sed -i 's/\\|/|/' tmp/HD.dat
perl -pi -e 's/[^[:ascii:]]//g' tmp/HD.dat

# import queries
PGPASSWORD=eaglelogger psql -U eaglelogger -h postgres <<-EOSQL
  \i import.sql
EOSQL
